---
# dataverse/tasks/main.yml

- include: dataverse-prereqs.yml
  tags: prereqs

- include: dataverse-apache.yml
  tags: apache

- include: dataverse-shibboleth.yml
  when: dataverse.shibboleth.enabled == True
  tags: shibboleth

- include: dataverse-postgres.yml
  tags: postgres

- include: dataverse-glassfish.yml #changed to asadmin restart-domain, not sure if this will work on fresh install
  tags: glassfish

- include: dataverse-solr.yml #fails here if collection1 already added, consider swapping out with ansible galaxy
  tags: solr

- include: dataverse-install.yml
  tags: dataverse

- include: dataverse-postinstall.yml
  tags: postinstall
